"""added realtionships

Revision ID: 0ce168d4c012
Revises: 8c40cfad8af1
Create Date: 2026-08-16 19:59:49.800816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce168d4c012'
down_revision: Union[str, Sequence[str], None] = '8c40cfad8af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ea_tokens')
    op.drop_table('stat_update')
    op.drop_table('league_hub_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_hub_info',
    sa.Column('league_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calendar_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summaries', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_synced', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('league_id', name=op.f('league_hub_info_pkey'))
    )
    op.create_table('stat_update',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_info_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calendar_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('did_game_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_players_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_passing_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_rushing_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_receiving_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_defense_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_punt_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_kick_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_team_stat_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_standings_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('did_teams_sync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_synced', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['league_info_id'], ['league_hub_info.league_id'], name=op.f('stat_update_league_info_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stat_update_pkey')),
    sa.UniqueConstraint('league_info_id', 'week_index', 'stage_index', 'calendar_year', name=op.f('_stat_update_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ea_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ea_tokens_pkey'))
    )
    # ### end Alembic commands ###
